name: create-asset
on: 
  push:
    branches:
      - main
jobs:
  build-asset:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup NodeJS and PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install dependencies
        run: pnpm install
      - name: Build asset
        run: pnpm build
      - name: Create Tag
        run: git tag $(git rev-parse --short HEAD)
      - name: Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/export53.min.js
        