name: create-tag
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push-tag:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create Tag
        run: |
          git tag $(git rev-parse --short HEAD)
          git push origin $(git rev-parse --short HEAD)
        