name: upload-asset
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup NodeJS and PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install dependencies
        run: pnpm install
      - name: Build asset
        run: pnpm build
      - name: Release
        run: gh release create $(node -p -e "require('./package.json').version") ./dist/export53.min.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        