name: upload-asset
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup NodeJS and PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install dependencies
        run: pnpm install
      - name: Build asset
        run: pnpm build
      - name: Create Tag
        run: pnpm release
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latests
    steps:
      - name: Setup GIT
        uses: actions/setup-git@v2
      - name: Configure Git identity
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
      - name: Get the latest tag
        id: get_tag
        run: echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/export53.min.js
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          title: Release ${{ steps.get_tag.outputs.TAG_NAME }}
        